<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/balance.proto

namespace GPBMetadata\Protos;

class Balance
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aec010a1470726f746f732f62616c616e63652e70726f746f1218506461" .
            "4170692e506870436c69656e742e42616c616e6365224f0a0742616c616e" .
            "6365120a0a02696418012001280912380a0a70726f706572746965731802" .
            "2001280b32242e5064614170692e506870436c69656e742e42616c616e63" .
            "652e50726f7065727469657322610a0a50726f7065727469657312100a08" .
            "63757272656e6379180120012805120e0a06757365724964180220012805" .
            "120e0a066e6f64654964180320012805120e0a06616d6f756e7418042001" .
            "280212110a0969735f616374697665180520012808620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

