<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/personal.proto

namespace PdaApi\PhpClient\Personal;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>PdaApi.PhpClient.Personal.Personal</code>
 */
class Personal extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>.PdaApi.PhpClient.Personal.Properties properties = 3;</code>
     */
    private $properties = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \PdaApi\PhpClient\Personal\Properties $properties
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Protos\Personal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.PdaApi.PhpClient.Personal.Properties properties = 3;</code>
     * @return \PdaApi\PhpClient\Personal\Properties
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * Generated from protobuf field <code>.PdaApi.PhpClient.Personal.Properties properties = 3;</code>
     * @param \PdaApi\PhpClient\Personal\Properties $var
     * @return $this
     */
    public function setProperties($var)
    {
        GPBUtil::checkMessage($var, \PdaApi\PhpClient\Personal\Properties::class);
        $this->properties = $var;

        return $this;
    }
}
